digest/org/__init__.py
from flask import Blueprint
org = Blueprint('org', __name__, template_folder='templates', static_folder='static')

import digest.org.views

digest/org/views.py
from digest.org import org
from digest.content import Content
from digest.containers import Organization, OrganizationPermission
from digest.util import render_template_or_json
from digest.login.user import get_session_user, login_required, admin_required
from flask import request, redirect, url_for, flash, send_from_directory, get_flashed_messages, jsonify
from markdown import markdown
from digest import app, db, allowed_file
from werkzeug import secure_filename
import os
import time
import json
from PIL import Image

def render_view(template, org, _content=None, _units=None, _subjects=None, **kwargs):
    if not _content:
        _content = org.content
    return render_template_or_json(template, org=org, content=_content,
                                   units=_units, subjects=_subjects, **kwargs)

@org.route("/")
@org.route("/list")
@login_required
def list():
    return render_template_or_json("list.html", orgs=Organization.query)

@org.route("/<id>")
@login_required
def view(id):
    org = Organization.query.get_or_404(id)
    return render_view("view.html", org=org)

@org.route("/<id>/submit", methods=['POST'])
@login_required
def submit(id):
    org = Organization.query.get_or_404(id)
    Content(request.form['title'], org, get_session_user(), request.form['text'])
    return redirect(url_for('.view', id=id))


@org.route("/<id>/subscribe")
@login_required
def subscribe(id):
    org = Organization.query.get_or_404(id)
    org.subscribe(get_session_user())
    return redirect(url_for('.list'))

@org.route("/<id>/unsubscribe")
@login_required
def unsubscribe(id):
    cls = Organization.query.get_or_404(id)
    cls.unsubscribe(get_session_user())
    return redirect(url_for('.list'))

@org.route("/create", methods=['POST'])
@admin_required
def create():
    org = Organization(request.form['name'])
    OrganizationPermission(get_session_user(), org, is_admin=True)
    return redirect(url_for('.view', id=org.id))

digest/org/templates/list.html
{% extends "base-scaffolding.html" %}
{% block title %}Class List{% endblock %}
{% block breadcrumbs %}
        <li class="active">Class</li>
{% endblock %}
{% block content %}
<table class="table table-striped table-bordered">
    <thead>
    <tr>
        <th>Organization</th>
        <th>Subscribe</th>
    </tr>
    </thead>
    <tbody>
{% for org in orgs %}
    <tr>
        <td><a href="{{ url_for('org.view', id=org.id) }}">{{ org.name }}</a></td>
        {% if org.is_subscribed() %}
            <td><a href="{{ url_for('org.unsubscribe', id=org.id) }}">
                <button type="button" class="btn btn-danger">Unsubscribe</button>
            </a></td>
        {% else %}
            <td><a href="{{ url_for('org.subscribe', id=org.id) }}">
                <button type="button" class="btn btn-success">Subscribe</button>
            </a></td>
        {% endif %}
    </tr>
{% endfor %}
{% if user.is_admin %}
    <form method="post" action="{{ url_for('org.create') }}">
    <tr>
        <td><input type="text" name="name"></td>
            <td>
                <input type="submit" class="btn btn-success"/>
            </td>
    </tr>
    </form>
{% endif %}
</tbody>
</table>
{% endblock %}

digest/org/templates/view.html
{% extends "base-scaffolding.html" %}
{% block title %}Organization {{ org.name }}{% endblock %}
{% block breadcrumbs %}
        <li><a href="{{ url_for('.list') }}">Organization</a></li>
        <li class="active">{{ org.name }}</li>
{% endblock %}
{% block content %}
<div id="content-area">
    {% if org.has_permission() %}
    <form id="content-submit" enctype="multipart/form-data" method="post" action="{{ url_for('.submit', id=org.id) }}">
        <label for="content-title">Title: </label>
        <input id="content-title" name="title"/>
        <label for="content-text">Text: </label>
        <textarea id="content-text" name="text"></textarea>
        <input type="submit">Submit</form>
    </form>
    {% endif %}
{% for c in content %}
    {% if loop.index % 3 == 1 %}
        <table class="content-table">
            <tr>
    {% endif %}
                <td>
                    {{ c.get_print() |safe }}
                </td>
                {% if loop.index % 3 == 0 or loop.last %}
            </tr>
        </table>
    {% endif %}
{% endfor %}
</div>
{% endblock %}